### PR TITLE
Restore "Update project dependencies to newest"

### PR DESCRIPTION
**Pull request by shadowhand**
This reverts commit d9f5d1955b02bc7bcd0d70597fe11963d03ada34.

Refs #104

### CODE REVIEW

**Comment by shadowhand** [comment]
Hold off merging this until #105 is landed and tagged.

**Comment by elazar** [comment]
I'm confused. Why do we need this revert?

**Comment by shadowhand** [comment]
@elazar I want to release a 0.15.1 that fixes the env thing before releasing 0.16. I wouldn't have reverted except that #104 contains a breaking change (dropping NegotiatorConfiguration).

**Comment by elazar** [comment]
Ah, fair enough then.

**Pull request merged**
