### PR TITLE
Application refactor cleanup

### PR DESCRIPTION
**Pull request by elazar**
* Remove `Traversable` support from `Middleware\Collection`
* Remove `Application` in favor of having its logic inline in the bootstrap file

Addresses residual issues from #45

### CODE REVIEW

**Comment by shadowhand** [comment]
:+1:

**Comment by shadowhand** [comment]
What does the new bootstrap look like?

**Comment by elazar** [comment]
@shadowhand Something along these lines, I think:

```php
// Include Composer autoloader
require __DIR__ . '/../vendor/autoload.php';

// Configure the dependency injection container
$injector = new \Auryn\Injector;
$configuration = new \Spark\Configuration\DefaultConfigurationSet;
$configuration->apply($injector);

// Configure middleware
// It's possible we could move this into DefaultConfigurationSet
// and just let the user override it as needed
$injector->alias(
    '\\Spark\\Middleware\\Collection',
    '\\Spark\\Middleware\\DefaultCollection'
);

// Configure the router
$injector->prepare(
    '\\Spark\\Router',
    function(\Spark\Router $router) {
        // ...
    }
);
// Or, alternatively:
$injector->alias('\\Spark\\Router', '\\My\\RouterSubclass');

// Bootstrap the application
$dispatcher = $injector->make('\\Relay\\Relay');
$dispatcher(
    $injector->make('Psr\\Http\\Message\\ServerRequestInterface'),
    $injector->make('Psr\\Http\\Message\\ResponseInterface')
);
```

**Comment by shadowhand** [comment]
Cool, I think we can optimize that a little bit by moving the collection into the configuration. And maybe we can also improve the router somehow.

**Comment by elazar** [comment]
@shadowhand There's a potential issue with moving the collection into configuration: if we use a type alias, there's no way to override it except with another alias. That is, the user loses the ability to do something like this instead at that point:

```php
$injector->define('\\Spark\\Middleware\\Collection, [':middleware' => [ /* ... */ ]]);
```

**Comment by dolfelt** [comment]
I think the collection should stay in Middleware to keep it separate. This isn't really related to configuration of the injector, imo.

**Comment by elazar** [comment]
@dolfelt Not sure I follow it. It's related to injector configuration insofar as it's [used for Relay configuration](https://github.com/sparkphp/spark/blob/ea583773486f239ad7d4de644251584f507b51c5/src/Configuration/RelayConfiguration.php#L23-L28).

**Pull request merged**
