### PR TITLE
Use Destrukt for config and middleware sets

### PR DESCRIPTION
**Pull request by shadowhand**
Enables a standard, immutable interface to be used for both config and
middleware sets. Also ensures that config and middleware is never
duplicated.

### CODE REVIEW

**Comment by shadowhand** [comment]
Build is failing because of relayphp/Relay.Relay#21

**Comment by elazar** [comment]
:+1:

**Comment by shadowhand** [comment]
Build is now fixed. Merging this.

**Comment by Yahasana** [comment]
it'd be nice the namespace and git repos of `destrukt` are placed in `sparkphp`.
ref [About Personal Github Accounts](http://fabien.potencier.org/about-personal-github-accounts.html)

**Comment by shadowhand** [comment]
Moved to @destruktphp.

**Comment by Yahasana** [comment]
:+1: :100:

**Pull request merged**
