### PR TITLE
Modify configuration set to allow additions

### PR DESCRIPTION
**Pull request by shadowhand**
Enables the user to add custom config to the default set.

Refs #60

### CODE REVIEW

**Comment by shadowhand** [comment]
Usage example:

```php
use Auryn\Injector;
use josegonzalez\Dotenv\Loader;

class EnvConfiguration implements ConfigurationInterface
{
    public function apply(Injector $injector)
    {
        $loader = $injector->make(Loader::class)->parse();
        $config = $loader->toArray();

        $injector->define('Aura\Sql\PdoInterface', [
            ':dsn'      => $config['dbdsn'],
            ':username' => $config['dbuser'],
            ':password' => $config['dbpass'],
        ]);
    }
}
```

**Comment by dolfelt** [comment]
I think it's nice to be able to share the settings though, and have the configuration of each dependency separated. I guess this could easily share the loaded settings with the injector if the user wanted to.

I want to make sure that someone can come in here and get something rolling pretty quick. Sane defaults. Spark should be quick out of the gate, and super robust. If that means including lots of samples in our example project, then let's do that.

Overall though, I completely agree with the `add` method. I think that will make configuration setup much easier. :+1:

**Comment by ameech** [comment]
I agree with @dolfelt on making it super easy to get rolling. I was setting up a project last night and it was pretty annoying trying to piece together things, I blame my lack of understanding mostly.

**Comment by shadowhand** [comment]
@dolfelt right, my example is just an example... we can do it better by having a `Settings` class if we want, but I think we need `add` for sure:

```php
$configuration = (new \Spark\Configuration\DefaultConfigurationSet)
    ->add(Acme\Configuration\EnvLoaderConfiguration);
    ->add(Acme\Configuration\DatabaseConfiguration);
    ->add(Acme\Configuration\RedisConfiguration);

**Comment by elazar** [comment]
@shadowhand Should be make `ConfigurationSet` immutable?

**Comment by elazar** [comment]
@shadowhand Side note on the usage example: I'd prefer we keep things as lazy as possible. If a domain doesn't require configuration to be loaded, we shouldn't load it.

**Comment by shadowhand** [comment]
@elazar I was trying to decide if it should be immutable, but I don't really see any value to that. The configuration set will only be run once.

**Comment by elazar** [comment]
:+1:

**Pull request merged**
